In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a.ndim

1

In [4]:
a

array([1, 2, 3])

In [5]:
a.shape

(3,)

In [9]:
b = np.array([[1,2,3],
             [4,5,6]])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.ndim

2

In [13]:
b.shape

(2, 3)

In [14]:
b.dtype

dtype('int32')

In [15]:
b.itemsize

4

In [16]:
b[0]

array([1, 2, 3])

In [17]:
b[0,1]

2

In [18]:
b[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
b[1,2]

6

In [31]:
b[1,2]=20 # update elements

In [32]:
b

array([[ 1,  2,  3],
       [ 4,  5, 20]])

In [33]:
np.zeros((2,2),dtype='int32')

array([[0, 0],
       [0, 0]])

In [34]:
np.zeros((3,3),dtype='int32')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [37]:
np.ones((3,2))  # by defaults float no. taken

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## random decimal

In [55]:
np.random.randint(3,15)

11

In [64]:
np.random.randint(3,15,size=(3,3))

array([[11, 10, 13],
       [12, 10, 12],
       [11,  3, 14]])

In [66]:
np.random.randint(3,45,size=(4,4))

array([[15, 34, 31, 42],
       [14, 28, 17, 30],
       [35, 14, 16, 40],
       [ 3, 14, 25,  6]])

## identical matrix

In [70]:
np.identity(4)   # by defaults float taken

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [71]:
np.identity(4,dtype='int32') 

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

## matrix calculations

In [72]:
a = np.array([[1,2,3],[4,5,6]])

In [75]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
b = np.array([[7,8,9],[10,11,12]])

In [77]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [79]:
  a+b #  addition

array([[ 8, 10, 12],
       [14, 16, 18]])

In [80]:
  a*b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [81]:
a-b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [82]:
a/b

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [83]:
a**b

array([[          1,         256,       19683],
       [    1048576,    48828125, -2118184960]])

## statistics og Matrix

In [84]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
np.min(a)

1

In [86]:
np.max(a)

6

In [87]:
np.sum(a)

21

In [88]:
np.std(a)

1.707825127659933

In [93]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
a.shape

(2, 3)

In [97]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [98]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [108]:
b = np.genfromtxt("C:\\Users\\rohan\\OneDrive\\Desktop\\que.txt", delimiter='O')

ValueError: Some errors were detected !
    Line #9 (got 2 columns instead of 1)