In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [7]:
a.ndim

1

In [8]:
a = np.array([100,200,300])

In [10]:
a[2]  # indexing array

300

In [11]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a.ndim

2

In [15]:
a = np.array(['1',2,4])

In [16]:
a

array(['1', '2', '4'], dtype='<U11')

 ## array is collection of simmilar data

In [17]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
a.dtype  # by defults its 32 bit ,memory allocation 

dtype('int32')

In [24]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype = 'int64')  # we can give int64 also

In [25]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

In [26]:
a.dtype  

dtype('int64')

In [34]:
a.itemsize

8

In [29]:
import sys 

In [31]:
sys.getsizeof(a)

200